### ISSUE TITLE
New service: backup

### ISSUE THREAD

**Issue by yscialom** [yscialom/pinanas#18]
Add new application
===================
https://hub.docker.com/r/linuxserver/duplicati

Test it
-------
With:
* Amazon S3 Glacier (IA and or IR, Deep Archive out of scope)
* Google Drive

**Comment by glevil** [comment]
First test : rsnapshot - differential backup tools

**Comment by yscialom** [comment]
https://hub.docker.com/r/linuxserver/duplicati
Amazon S3 Glacier

**Comment by yscialom** [comment]
Relevant: https://github.com/duplicati/duplicati/issues/4882
