### ISSUE TITLE
Ducumentation: Cloudflare - API

### ISSUE THREAD

**Issue by glevil** [yscialom/pinanas#28]
In "setting.yml" file, fulfill this : 
    PINANAS_DNS_PROVIDER_NAME:
    PINANAS_DNS_PROVIDER_VARS:

with : 
PINANAS_DNS_PROVIDER_NAME: cloudflare   ## lowercase only !!!
PINANAS_DNS_PROVIDER_VARS:
- name: CLOUDFLARE_API_KEY
  value: xxxx
- name: CLOUDFLARE_EMAIL
  value: (your login email to your cloudflare account)
- name: CLOUDFLARE_DNS_API_TOKEN
  value: xxxx
- name: CLOUDFLARE_ZONE_API_TOKEN
  value: xxxx

# see : https://developers.cloudflare.com/api/tokens/create to create API_TOKEN

**Comment by yscialom** [comment]
Duplicates #66
