### ISSUE TITLE
Bug and Issue - Nextcloud users are not added as administrator

### ISSUE THREAD

**Issue by glevil** [yscialom/pinanas#84]
**Describe the bug**
By default, with current settings, all users are added as "admins" and "users" in Authelia groups.
In Nextcloud, users are added like following:
- "admin" (not based on Authelia)
-  "users" (based on Authelia)

=> "admin" is administrator of Nextcloud but password seem defined by the application - password need to be reset in docker with command "sudo -u abc php /config/www/nextcloud/occ resetpassword admin"

=> "users" are basics users and not administrator.

**Expected behavior**
As all users defined in settings.y*ml are added to "admins" group in Authelia, it's expected they are "admin" in Nextcloud.

**Additional context**
This bug is reported as a bug and issue.
=> Bug: explained / see if "admin" user created by default could be overwrighted.
=> Issue: a variable {{ users.group }} for users in settings.y*ml file could be added to choose for each one the profil.

**Comment by yscialom** [comment]
Idea: once a Authelia admin user has been created in Nextcloud, remove the `admin` user:
```
occ user:delete admin
```
To be added as a cron task

**Comment by yscialom** [comment]
Blocked by https://github.com/nextcloud/user_oidc/pull/502
