### ISSUE TITLE
Rename docker-templates/ + .yml -> .yml.j2

### ISSUE THREAD

**Issue by yscialom** [yscialom/pinanas#90]

**Comment by glevil** [comment]
What the need to rename these files? With « .j2 », they will be copied in installation directory… but we only want the docker-compose.yaml file, not all templates.?

**Comment by yscialom** [comment]
`templates/` is meant to mimic the target file hierarchy, but with jinja templates instead of plain files.

Currently `docker-template/` is an exception as this directory is not meant to appear in the target. It works, but if we can get rid of an exception, let's do it! As PiNanas will grow in complexity, the fewer exceptions the better.

A solution must be found. This solution should enable us to rename its content to `*.yaml.j2` as those files are indeed jinja2 template files.

**Comment by glevil** [comment]
Ok, knowing that docker-templates/ will be copied in the target directory, can we plan to delete it afterwards via "distclean.sh"?

**Comment by yscialom** [comment]
>docker-templates/ will be copied in the target directory
The aim is for it not to be copied I'd say
